### ISSUE TITLE
Extracting specfic indexes?

### ISSUE THREAD

**Issue by kalkal11** [kinfolk0117/ComfyUI_SimpleTiles#2]
Hey, this could be super useful for building a manual tiled upscale however, is there a way that you're aware of to select certain indexes from the split image? I have some ideas I want to try out which don't necessarily mean that I want to process sequentially.

Thanks!

**Comment by kinfolk0117** [comment]
https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite has some nodes for spliting and merging batches of images.
