### ISSUE TITLE
How to calculate tilesize for tilesplit?

### ISSUE THREAD

**Issue by MortalSage** [kinfolk0117/ComfyUI_SimpleTiles#3]
I want to use tilesplit in combination with img2img and tilemerge for a tiled upscaler.
Currently I am facing huge issues with missing pixels when using overlap.
I'm trying to calculate how much larger my tiles need to be to compensate the loss from tilesplit with overlap.

I mean, If I use tilesplit as is for splitting a picture 1024x1024 in 4 parts, usually you would say 512x512px is a perfect split.
But then I lose all overlap pixels on the right and lower border.
Now I balanced this by spreading these pixels on top of each tile, so with 64px overlap, I make the tilesize 512+32px and get 4 tiles (544x544px) which can be merged into a full 1024x1024 img without losing anything.

But this gets increasingly complex with increasing tilecount and additionally when I have assymetrical pictures.
My main antagonist for compensating overlap is, that the height overlap is not fixed, but dynamically calculated. 
So when I compensate width, my height goes haywire.
And than I need to round values because img2img can only work with multiples of 8px. 

Do you have any solution for this?
I suggest making overlap height = overlap width or to make two separate variables.

**Comment by kinfolk0117** [comment]
Added two updated nodes DynamicTileSplit/DynamicTileMerge that probably work better in your example. Give it the tile size and it will figure out how many tiles are needed.
